# Generated by Django 5.2 on 2025-05-14 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Aadhar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('father', models.CharField(max_length=32)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('phone', models.PositiveIntegerField()),
                ('profile', models.ImageField(upload_to='profiles')),
                ('mail', models.CharField(default='abc@gmail.com')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gender')),
            ],
        ),
    ]
